# Generated by Django 3.2.3 on 2021-07-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companies_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='main_image',
            field=models.ImageField(default='media/default2.jpg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='logo',
            field=models.ImageField(default='media/default.jpg', upload_to='media/'),
        ),
    ]
